[project]
name = "odoo-addons-oca-server-backend"
version = "18.0.20241127.0"
dependencies = [
    "odoo-addon-base_user_role==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
